name: Snake Game

on:
  schedule:
    # Atualiza a cada 5 horas
    - cron: "0 */5 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Baixa o repositório
      - uses: actions/checkout@v2

      # Gera os arquivos da cobrinha
      - uses: Platane/snk@master
        with:
          github_user_name: samanthaalves26
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Publica no branch output
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
